/**
 * The ONE place in this codebase allowed to reach for the live Cloudflare
 * D1 binding (Brief 011 §7). Every repository function in src/lib/db/
 * takes `db: D1Database` as an explicit parameter instead — easy to call
 * from a test with a different D1Database instance, no hidden global
 * state, no DI container.
 *
 * `Astro.locals.runtime.env` was removed in Astro v6 / this adapter
 * version (@astrojs/cloudflare 14.x) — the current, only supported way to
 * reach a binding is the `cloudflare:workers` virtual module's `env`
 * export. Its ambient types come from `worker-configuration.d.ts`
 * (regenerated by `npm run typecheck`, gitignored — see .gitignore and
 * docs/TECHNICAL_ARCHITECTURE.md).
 */
import { env } from "cloudflare:workers";

export function getDb(): D1Database {
  return env.DB;
}
