-- ============================================================================
-- Divine Motion V2 — 001_initial.sql (DRAFT — NOT EXECUTED, NOT APPLIED)
-- ============================================================================
-- Status: design draft for Phase 4 / Data Architecture Brief 009, revised
-- per Review 009A. This file is for audit and discussion. Do not run it
-- against any D1 database (local, staging, or production) until it is
-- explicitly reviewed and approved. See docs/DATA_ARCHITECTURE.md.
--
-- Conventions used throughout (see DATA_ARCHITECTURE.md §18 for the
-- justification of each):
--   - Primary keys: INTEGER PRIMARY KEY AUTOINCREMENT (SQLite rowid alias,
--     AUTOINCREMENT to guarantee no id reuse after a hard delete), except
--     page_seo, which uses page_key directly as primary key (§9/§13).
--   - Timestamps: INTEGER, Unix milliseconds (UTC), suffixed _at.
--   - Booleans: INTEGER, CHECK(col IN (0,1)).
--   - Enums: TEXT + CHECK(col IN (...)) — SQLite has no native enum type.
--   - FR/EN: denormalized _fr/_en column pairs per ADR-007, never a
--     generic translations table.
--   - Draft/publish (Review 009A — one single mechanism, no exceptions):
--     every publicly-editable entity (work_items, services, testimonials,
--     and the 5 page-content tables) carries `status` ('draft'|
--     'published') and a self-referencing `draft_of_id`. The row with
--     status='published' is what the public site reads; at most one
--     status='draft' row may exist per published row (partial unique
--     index on draft_of_id). Editing a published item edits its draft
--     shadow, never the published row itself, until an explicit Publish
--     action copies the draft's fields onto the published row inside a
--     transaction. Preview reads the draft row when one exists; the
--     public site NEVER reads a status='draft' row. See
--     DATA_ARCHITECTURE.md §13.
--   - No generic JSON content blob anywhere in live content tables
--     (ADR-004). The one narrow, justified exception is
--     content_snapshots.snapshot_json — a rollback safety net, not a
--     content field (see DATA_ARCHITECTURE.md §15).
--
-- PRAGMA foreign_keys = ON; must be set per-connection by the Worker/D1
-- binding — D1 enables this by default, but it is called out here as an
-- explicit implementation requirement, not an assumption.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- MEDIA
-- Represents web-master files stored in R2. D1 holds metadata only — never
-- the binary itself, never a permanent CDN URL (derived at render time from
-- storage_key). See docs/MEDIA_ARCHITECTURE.md, ADR-005, ADR-006.
-- ----------------------------------------------------------------------------
CREATE TABLE media (
  id                              INTEGER PRIMARY KEY AUTOINCREMENT,

  -- R2 object key, generated by the Worker at upload-authorization time
  -- (ULID-based, e.g. "media/01J9X.../original.jpg") — deliberately NOT the
  -- same value as `id`, so the id sequence never leaks storage layout and
  -- storage keys never need to change if a row is ever re-keyed.
  storage_key                     TEXT NOT NULL UNIQUE,
  original_filename                TEXT,
  mime_type                       TEXT NOT NULL,
  size_bytes                      INTEGER NOT NULL,
  width                            INTEGER,
  height                           INTEGER,

  -- MVP: images only. Video (mentioned as a Divine Motion service) has no
  -- storage/delivery pipeline decided yet — see DATA_ARCHITECTURE.md §29
  -- Open Questions. Not silently modeled here.
  media_type                      TEXT NOT NULL DEFAULT 'image'
                                   CHECK (media_type IN ('image')),

  alt_fr                           TEXT,
  alt_en                           TEXT,
  focal_x                         INTEGER NOT NULL DEFAULT 50
                                   CHECK (focal_x BETWEEN 0 AND 100),
  focal_y                         INTEGER NOT NULL DEFAULT 50
                                   CHECK (focal_y BETWEEN 0 AND 100),

  -- Upload lifecycle (ADR-006 presigned direct upload): a row is created
  -- the moment an upload is authorized, before the file lands in R2, so no
  -- upload can ever leave an incoherent/missing row (brief §23). No
  -- 'processing' state: Review 009A removed it — there is no real
  -- asynchronous transformation step at MVP (Cloudflare Images/Resizing
  -- transform on delivery, not at upload time), so a state nothing ever
  -- sets is not modeled.
  processing_status               TEXT NOT NULL DEFAULT 'pending'
                                   CHECK (processing_status IN
                                     ('pending', 'uploaded',
                                      'ready', 'failed', 'abandoned')),

  -- Publication rights live at the media level (source of truth), enforced
  -- at the usage/publish level via trigger — see §16/§24 in the report and
  -- the triggers at the bottom of this file.
  publication_rights_confirmed    INTEGER NOT NULL DEFAULT 0
                                   CHECK (publication_rights_confirmed IN (0,1)),
  publication_rights_note         TEXT,
  publication_rights_confirmed_at INTEGER,

  uploaded_at                     INTEGER NOT NULL,
  created_at                      INTEGER NOT NULL,
  updated_at                      INTEGER NOT NULL,
  -- Soft delete (trash). NULL = active. Set = pending purge after the
  -- retention window (see docs/MEDIA_ARCHITECTURE.md).
  deleted_at                      INTEGER,

  created_by                      TEXT,
  updated_by                      TEXT
);

CREATE INDEX idx_media_processing_status ON media(processing_status);
CREATE INDEX idx_media_deleted_at ON media(deleted_at);
CREATE INDEX idx_media_created_at ON media(created_at);


-- ----------------------------------------------------------------------------
-- WORK ITEMS
-- Curated selection of media for the public Travail page. NOT a Projects
-- model (ADR-003) — a work_item is a thin curation record, not a valuable
-- piece of content in itself; the asset it protects is `media`.
-- No `layout`/`block_type` column: composition is computed by the frontend
-- from (position, count, aspect ratio) — see DATA_ARCHITECTURE.md §6/§13.
-- No soft delete: removing a media from Travail is just deleting the
-- curation row; the media itself keeps its own lifecycle (brief §7).
--
-- Draft/publish (Review 009A): same draft-shadow-row mechanism as the
-- page-content tables, one single mechanism site-wide. `status='published'`
-- rows are what the public site reads; at most one `status='draft'` row
-- may exist per published row (`draft_of_id`). Editing a published item
-- edits its draft shadow, never the published row directly, until an
-- explicit Publish action copies the draft's fields onto the published
-- row. See DATA_ARCHITECTURE.md §13.
-- ----------------------------------------------------------------------------
CREATE TABLE work_items (
  id                     INTEGER PRIMARY KEY AUTOINCREMENT,
  status                 TEXT NOT NULL DEFAULT 'published'
                         CHECK (status IN ('draft', 'published')),
  draft_of_id             INTEGER REFERENCES work_items(id) ON DELETE CASCADE,

  media_id               INTEGER NOT NULL REFERENCES media(id) ON DELETE RESTRICT,

  -- Admin-side organization only — not used by public filtering today
  -- (the public page has none). Kept per CMS_SPEC's conceptual model,
  -- explicitly as forward-looking, not required by current rendering.
  category                TEXT CHECK (category IN ('wedding', 'portrait', 'event')),

  position                INTEGER NOT NULL,
  ratio                   TEXT NOT NULL,
  caption_fr               TEXT,
  caption_en               TEXT,
  alt_fr                   TEXT NOT NULL,
  alt_en                   TEXT NOT NULL,
  focal_x                 INTEGER NOT NULL DEFAULT 50 CHECK (focal_x BETWEEN 0 AND 100),
  focal_y                 INTEGER NOT NULL DEFAULT 50 CHECK (focal_y BETWEEN 0 AND 100),

  -- Quick on/off for an otherwise-ready item, independent from the
  -- draft/published lifecycle (CMS_SPEC lists "afficher/masquer" as a
  -- distinct admin action from editing).
  is_visible              INTEGER NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1)),

  -- Replaces home.ts's separately-curated "Work Preview" list: the
  -- homepage teaser is a subset of Travail, not a second parallel
  -- curation surface. See DATA_ARCHITECTURE.md §6.
  featured_on_home         INTEGER NOT NULL DEFAULT 0 CHECK (featured_on_home IN (0,1)),

  -- Independent FR/EN publication (ADR-007): a page never mixes languages,
  -- so an item whose EN caption isn't ready must be excluded from the EN
  -- Travail page even while it shows on FR.
  fr_status                TEXT NOT NULL DEFAULT 'draft'
                           CHECK (fr_status IN ('draft', 'published', 'archived')),
  en_status                TEXT NOT NULL DEFAULT 'draft'
                           CHECK (en_status IN ('draft', 'published', 'archived')),
  fr_published_at          INTEGER,
  en_published_at          INTEGER,

  created_at               INTEGER NOT NULL,
  updated_at               INTEGER NOT NULL,
  created_by                TEXT,
  updated_by                TEXT
);

CREATE INDEX idx_work_items_position ON work_items(position);
CREATE INDEX idx_work_items_media_id ON work_items(media_id);
CREATE INDEX idx_work_items_fr_status ON work_items(fr_status);
CREATE INDEX idx_work_items_en_status ON work_items(en_status);
CREATE INDEX idx_work_items_featured_on_home ON work_items(featured_on_home)
  WHERE featured_on_home = 1;
CREATE UNIQUE INDEX idx_work_items_one_draft_per_published
  ON work_items(draft_of_id) WHERE draft_of_id IS NOT NULL;
-- Public rendering must always filter status = 'published' in addition to
-- fr_status/en_status = 'published' — a draft shadow row is never public.


-- ----------------------------------------------------------------------------
-- SERVICES
-- Exactly 3 known MVP services (Mariages / Portraits & Lifestyle /
-- Événements). No `layout` column (Review 009A — removed): the three
-- compositions are a frontend design decision keyed off `slug`, a stable
-- identifier that never changes — not CMS content, so it does not live in
-- D1 at all. See DATA_ARCHITECTURE.md §7/§13. No soft delete: fixed,
-- near-permanent rows; `is_active` covers hiding one.
--
-- Draft/publish (Review 009A): same draft-shadow-row mechanism as
-- work_items and page content — see DATA_ARCHITECTURE.md §13.
-- ----------------------------------------------------------------------------
CREATE TABLE services (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  status             TEXT NOT NULL DEFAULT 'published'
                     CHECK (status IN ('draft', 'published')),
  draft_of_id         INTEGER REFERENCES services(id) ON DELETE CASCADE,

  -- Stable identifier the frontend uses to look up its (non-editable,
  -- code-owned) layout — see docs/DATA_ARCHITECTURE.md §7. UNIQUE is
  -- enforced only among published rows: a draft shadow legitimately
  -- shares its published row's slug.
  slug               TEXT NOT NULL,

  title_fr            TEXT NOT NULL,
  title_en            TEXT NOT NULL,
  description_fr      TEXT NOT NULL,
  description_en      TEXT NOT NULL,

  media_id            INTEGER NOT NULL REFERENCES media(id) ON DELETE RESTRICT,
  ratio               TEXT NOT NULL,
  image_alt_fr         TEXT NOT NULL,
  image_alt_en         TEXT NOT NULL,

  cta_label_fr         TEXT NOT NULL,
  cta_label_en         TEXT NOT NULL,

  position             INTEGER NOT NULL,
  is_active            INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),

  fr_status            TEXT NOT NULL DEFAULT 'draft'
                       CHECK (fr_status IN ('draft', 'published', 'archived')),
  en_status            TEXT NOT NULL DEFAULT 'draft'
                       CHECK (en_status IN ('draft', 'published', 'archived')),
  fr_published_at      INTEGER,
  en_published_at      INTEGER,

  created_at           INTEGER NOT NULL,
  updated_at           INTEGER NOT NULL,
  created_by            TEXT,
  updated_by            TEXT
);

CREATE INDEX idx_services_position ON services(position);
CREATE INDEX idx_services_is_active ON services(is_active);
CREATE INDEX idx_services_fr_status ON services(fr_status);
CREATE INDEX idx_services_en_status ON services(en_status);
CREATE UNIQUE INDEX idx_services_one_draft_per_published
  ON services(draft_of_id) WHERE draft_of_id IS NOT NULL;
-- slug is unique among published rows only — a draft shadow legitimately
-- shares its published row's slug (it is a pending edit of that same
-- service, not a new one).
CREATE UNIQUE INDEX idx_services_slug_published
  ON services(slug) WHERE status = 'published';

-- Service "01"/"02"/"03" eyebrow labels are derived from `position` at
-- render time, not stored (avoids a field that can drift from position).
-- Layout (wide-offset/split/text-image) is NOT a column here at all
-- (Review 009A) — it lives in frontend code, keyed by `slug`. See
-- DATA_ARCHITECTURE.md §7/§13.

CREATE TABLE service_features (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  service_id   INTEGER NOT NULL REFERENCES services(id) ON DELETE CASCADE,
  position     INTEGER NOT NULL,
  text_fr       TEXT NOT NULL,
  text_en       TEXT NOT NULL
);

CREATE INDEX idx_service_features_service_id ON service_features(service_id);


-- ----------------------------------------------------------------------------
-- TESTIMONIALS
-- Simple MVP model — no review system. Soft-deletable (brief §7: pulling a
-- testimonial down is a normal, reversible editorial action) — `deleted_at`
-- is only meaningful on a published row; discarding a draft shadow is a
-- hard DELETE of that row, not a soft delete.
--
-- Draft/publish (Review 009A): same draft-shadow-row mechanism as
-- work_items/services/page content — see DATA_ARCHITECTURE.md §13.
-- ----------------------------------------------------------------------------
CREATE TABLE testimonials (
  id                            INTEGER PRIMARY KEY AUTOINCREMENT,
  status                        TEXT NOT NULL DEFAULT 'published'
                                 CHECK (status IN ('draft', 'published')),
  draft_of_id                    INTEGER REFERENCES testimonials(id) ON DELETE CASCADE,

  author_name                   TEXT NOT NULL,
  quote_fr                       TEXT NOT NULL,
  quote_en                       TEXT NOT NULL,
  role_context_fr                 TEXT,
  role_context_en                 TEXT,

  -- Optional — a testimonial can be text-only.
  photo_media_id                 INTEGER REFERENCES media(id) ON DELETE RESTRICT,

  position                       INTEGER NOT NULL,
  is_visible                     INTEGER NOT NULL DEFAULT 1 CHECK (is_visible IN (0,1)),

  fr_status                      TEXT NOT NULL DEFAULT 'draft'
                                 CHECK (fr_status IN ('draft', 'published', 'archived')),
  en_status                      TEXT NOT NULL DEFAULT 'draft'
                                 CHECK (en_status IN ('draft', 'published', 'archived')),
  fr_published_at                INTEGER,
  en_published_at                INTEGER,

  created_at                     INTEGER NOT NULL,
  updated_at                     INTEGER NOT NULL,
  deleted_at                     INTEGER,
  created_by                      TEXT,
  updated_by                      TEXT
);

CREATE INDEX idx_testimonials_position ON testimonials(position);
CREATE INDEX idx_testimonials_deleted_at ON testimonials(deleted_at);
CREATE INDEX idx_testimonials_fr_status ON testimonials(fr_status);
CREATE INDEX idx_testimonials_en_status ON testimonials(en_status);
CREATE UNIQUE INDEX idx_testimonials_one_draft_per_published
  ON testimonials(draft_of_id) WHERE draft_of_id IS NOT NULL;


-- ----------------------------------------------------------------------------
-- PAGE CONTENT — one dedicated, independently-shaped table per page
-- (Option A, brief §4.F) for Accueil / Travail / Services / À propos /
-- Contact. Confidentialité is deliberately excluded — legal text stays
-- code/doc-driven, not casually CMS-editable (see DATA_ARCHITECTURE.md
-- §9). Each table carries the draft-shadow-row pattern (§14 in the
-- report): the row with status='published' is what the public site
-- renders; at most one status='draft' row may exist per published row
-- (draft_of_id), so mid-edit changes never touch the live row until an
-- explicit Publish action.
-- ----------------------------------------------------------------------------

CREATE TABLE home_content (
  id                                INTEGER PRIMARY KEY AUTOINCREMENT,
  status                           TEXT NOT NULL DEFAULT 'published'
                                    CHECK (status IN ('draft', 'published')),
  draft_of_id                      INTEGER REFERENCES home_content(id) ON DELETE CASCADE,

  hero_headline_fr                  TEXT NOT NULL,
  hero_headline_en                  TEXT NOT NULL,
  hero_subline_fr                   TEXT NOT NULL,
  hero_subline_en                   TEXT NOT NULL,
  hero_media_id                     INTEGER NOT NULL REFERENCES media(id) ON DELETE RESTRICT,
  hero_image_alt_fr                  TEXT NOT NULL,
  hero_image_alt_en                  TEXT NOT NULL,

  work_preview_label_fr              TEXT NOT NULL,
  work_preview_label_en              TEXT NOT NULL,
  work_preview_link_label_fr          TEXT NOT NULL,
  work_preview_link_label_en          TEXT NOT NULL,

  brand_statement_fr                 TEXT NOT NULL,
  brand_statement_en                 TEXT NOT NULL,

  services_preview_label_fr           TEXT NOT NULL,
  services_preview_label_en           TEXT NOT NULL,

  editorial_media_id                 INTEGER REFERENCES media(id) ON DELETE RESTRICT,
  editorial_image_alt_fr              TEXT,
  editorial_image_alt_en              TEXT,

  about_preview_label_fr              TEXT NOT NULL,
  about_preview_label_en              TEXT NOT NULL,
  about_preview_text_fr               TEXT NOT NULL,
  about_preview_text_en               TEXT NOT NULL,
  about_preview_media_id              INTEGER REFERENCES media(id) ON DELETE RESTRICT,
  about_preview_image_alt_fr           TEXT,
  about_preview_image_alt_en           TEXT,

  final_cta_headline_fr               TEXT NOT NULL,
  final_cta_headline_en               TEXT NOT NULL,

  -- Section visibility: one boolean column per known, fixed section
  -- (brief §33) — not a generic sections table, since the section set is
  -- fixed at schema-design time, not admin-defined.
  work_preview_visible                INTEGER NOT NULL DEFAULT 1 CHECK (work_preview_visible IN (0,1)),
  brand_statement_visible             INTEGER NOT NULL DEFAULT 1 CHECK (brand_statement_visible IN (0,1)),
  services_preview_visible            INTEGER NOT NULL DEFAULT 1 CHECK (services_preview_visible IN (0,1)),
  editorial_visible                   INTEGER NOT NULL DEFAULT 1 CHECK (editorial_visible IN (0,1)),
  about_preview_visible                INTEGER NOT NULL DEFAULT 1 CHECK (about_preview_visible IN (0,1)),

  fr_status                          TEXT NOT NULL DEFAULT 'draft'
                                     CHECK (fr_status IN ('draft', 'published')),
  en_status                          TEXT NOT NULL DEFAULT 'draft'
                                     CHECK (en_status IN ('draft', 'published')),
  fr_published_at                    INTEGER,
  en_published_at                    INTEGER,

  created_at                         INTEGER NOT NULL,
  updated_at                         INTEGER NOT NULL,
  created_by                          TEXT,
  updated_by                          TEXT
);

CREATE UNIQUE INDEX idx_home_content_one_published
  ON home_content(status) WHERE status = 'published';
CREATE UNIQUE INDEX idx_home_content_one_draft_per_published
  ON home_content(draft_of_id) WHERE draft_of_id IS NOT NULL;

-- Home's "Selected Work" and "Services" preview sections are DERIVED, not
-- separately curated: work_items.featured_on_home = 1 (ordered by
-- work_items.position) and the services table (ordered by
-- services.position), both filtered by is_active/is_visible + language
-- status. See DATA_ARCHITECTURE.md §6.


CREATE TABLE work_page_content (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  status              TEXT NOT NULL DEFAULT 'published'
                       CHECK (status IN ('draft', 'published')),
  draft_of_id         INTEGER REFERENCES work_page_content(id) ON DELETE CASCADE,

  title_fr              TEXT NOT NULL,
  title_en              TEXT NOT NULL,
  intro_fr               TEXT NOT NULL,
  intro_en               TEXT NOT NULL,
  cta_headline_fr         TEXT NOT NULL,
  cta_headline_en         TEXT NOT NULL,

  fr_status              TEXT NOT NULL DEFAULT 'draft' CHECK (fr_status IN ('draft', 'published')),
  en_status              TEXT NOT NULL DEFAULT 'draft' CHECK (en_status IN ('draft', 'published')),
  fr_published_at        INTEGER,
  en_published_at        INTEGER,

  created_at             INTEGER NOT NULL,
  updated_at             INTEGER NOT NULL,
  created_by               TEXT,
  updated_by               TEXT
);

CREATE UNIQUE INDEX idx_work_page_content_one_published
  ON work_page_content(status) WHERE status = 'published';
CREATE UNIQUE INDEX idx_work_page_content_one_draft_per_published
  ON work_page_content(draft_of_id) WHERE draft_of_id IS NOT NULL;


CREATE TABLE services_page_content (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  status              TEXT NOT NULL DEFAULT 'published'
                       CHECK (status IN ('draft', 'published')),
  draft_of_id         INTEGER REFERENCES services_page_content(id) ON DELETE CASCADE,

  title_fr              TEXT NOT NULL,
  title_en              TEXT NOT NULL,
  intro_fr               TEXT NOT NULL,
  intro_en               TEXT NOT NULL,
  approach_label_fr       TEXT NOT NULL,
  approach_label_en       TEXT NOT NULL,
  cta_headline_fr         TEXT NOT NULL,
  cta_headline_en         TEXT NOT NULL,

  fr_status              TEXT NOT NULL DEFAULT 'draft' CHECK (fr_status IN ('draft', 'published')),
  en_status              TEXT NOT NULL DEFAULT 'draft' CHECK (en_status IN ('draft', 'published')),
  fr_published_at        INTEGER,
  en_published_at        INTEGER,

  created_at             INTEGER NOT NULL,
  updated_at             INTEGER NOT NULL,
  created_by               TEXT,
  updated_by               TEXT
);

CREATE UNIQUE INDEX idx_services_page_content_one_published
  ON services_page_content(status) WHERE status = 'published';
CREATE UNIQUE INDEX idx_services_page_content_one_draft_per_published
  ON services_page_content(draft_of_id) WHERE draft_of_id IS NOT NULL;

-- Approach steps ("Échange/Préparation/Création") — small, fixed-length
-- (3, matching the design's 3-column grid), ordered list of distinct rich
-- text, hence a child table rather than fixed columns. The "01"/"02"/"03"
-- label is derived from `position`, not stored (same reasoning as
-- services.position above).
CREATE TABLE services_approach_steps (
  id                   INTEGER PRIMARY KEY AUTOINCREMENT,
  services_page_id      INTEGER NOT NULL REFERENCES services_page_content(id) ON DELETE CASCADE,
  position              INTEGER NOT NULL,
  title_fr               TEXT NOT NULL,
  title_en               TEXT NOT NULL,
  text_fr                 TEXT NOT NULL,
  text_en                 TEXT NOT NULL
);

CREATE INDEX idx_services_approach_steps_page_id ON services_approach_steps(services_page_id);


CREATE TABLE about_content (
  id                       INTEGER PRIMARY KEY AUTOINCREMENT,
  status                  TEXT NOT NULL DEFAULT 'published'
                           CHECK (status IN ('draft', 'published')),
  draft_of_id              INTEGER REFERENCES about_content(id) ON DELETE CASCADE,

  hero_title_fr              TEXT NOT NULL,
  hero_title_en              TEXT NOT NULL,
  hero_intro_fr               TEXT NOT NULL,
  hero_intro_en               TEXT NOT NULL,
  hero_media_id               INTEGER NOT NULL REFERENCES media(id) ON DELETE RESTRICT,
  hero_ratio                  TEXT NOT NULL,
  hero_image_alt_fr             TEXT NOT NULL,
  hero_image_alt_en             TEXT NOT NULL,

  story_label_fr               TEXT NOT NULL,
  story_label_en               TEXT NOT NULL,

  approach_label_fr             TEXT NOT NULL,
  approach_label_en             TEXT NOT NULL,

  breathing_media_id           INTEGER REFERENCES media(id) ON DELETE RESTRICT,
  breathing_ratio               TEXT,
  breathing_image_alt_fr         TEXT,
  breathing_image_alt_en         TEXT,

  human_note_text_fr            TEXT NOT NULL,
  human_note_text_en            TEXT NOT NULL,
  human_note_media_id           INTEGER REFERENCES media(id) ON DELETE RESTRICT,
  human_note_ratio               TEXT,
  human_note_image_alt_fr        TEXT,
  human_note_image_alt_en        TEXT,

  final_cta_headline_fr         TEXT NOT NULL,
  final_cta_headline_en         TEXT NOT NULL,

  fr_status                    TEXT NOT NULL DEFAULT 'draft' CHECK (fr_status IN ('draft', 'published')),
  en_status                    TEXT NOT NULL DEFAULT 'draft' CHECK (en_status IN ('draft', 'published')),
  fr_published_at              INTEGER,
  en_published_at              INTEGER,

  created_at                   INTEGER NOT NULL,
  updated_at                   INTEGER NOT NULL,
  created_by                     TEXT,
  updated_by                     TEXT
);

CREATE UNIQUE INDEX idx_about_content_one_published
  ON about_content(status) WHERE status = 'published';
CREATE UNIQUE INDEX idx_about_content_one_draft_per_published
  ON about_content(draft_of_id) WHERE draft_of_id IS NOT NULL;

CREATE TABLE about_story_paragraphs (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  about_id        INTEGER NOT NULL REFERENCES about_content(id) ON DELETE CASCADE,
  position        INTEGER NOT NULL,
  text_fr          TEXT NOT NULL,
  text_en          TEXT NOT NULL
);

CREATE INDEX idx_about_story_paragraphs_about_id ON about_story_paragraphs(about_id);

CREATE TABLE about_approach_items (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  about_id        INTEGER NOT NULL REFERENCES about_content(id) ON DELETE CASCADE,
  position        INTEGER NOT NULL,
  word_fr          TEXT NOT NULL,
  word_en          TEXT NOT NULL,
  text_fr          TEXT NOT NULL,
  text_en          TEXT NOT NULL
);

CREATE INDEX idx_about_approach_items_about_id ON about_approach_items(about_id);


CREATE TABLE contact_content (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  status                TEXT NOT NULL DEFAULT 'published'
                         CHECK (status IN ('draft', 'published')),
  draft_of_id           INTEGER REFERENCES contact_content(id) ON DELETE CASCADE,

  hero_title_fr           TEXT NOT NULL,
  hero_title_en           TEXT NOT NULL,
  hero_subtext_fr          TEXT NOT NULL,
  hero_subtext_en          TEXT NOT NULL,

  details_label_fr         TEXT NOT NULL,
  details_label_en         TEXT NOT NULL,

  closing_note_fr          TEXT NOT NULL,
  closing_note_en          TEXT NOT NULL,

  fr_status                TEXT NOT NULL DEFAULT 'draft' CHECK (fr_status IN ('draft', 'published')),
  en_status                TEXT NOT NULL DEFAULT 'draft' CHECK (en_status IN ('draft', 'published')),
  fr_published_at          INTEGER,
  en_published_at          INTEGER,

  created_at               INTEGER NOT NULL,
  updated_at               INTEGER NOT NULL,
  created_by                 TEXT,
  updated_by                 TEXT
);

CREATE UNIQUE INDEX idx_contact_content_one_published
  ON contact_content(status) WHERE status = 'published';
CREATE UNIQUE INDEX idx_contact_content_one_draft_per_published
  ON contact_content(draft_of_id) WHERE draft_of_id IS NOT NULL;

-- Contact's "Coordonnées" list (email, Instagram) is DERIVED from
-- site_settings, not a separately curated list — same field, one source
-- of truth, no duplication with the footer.


-- ----------------------------------------------------------------------------
-- SITE SETTINGS — singleton, strictly typed. Deliberately NOT a key/value
-- table: the field set is small and fixed (brief §34), so real columns are
-- simpler and safer than key/value + a whitelist.
-- ----------------------------------------------------------------------------
CREATE TABLE site_settings (
  id                            INTEGER PRIMARY KEY CHECK (id = 1),

  brand_name                     TEXT NOT NULL DEFAULT 'Divine Motion',
  contact_email                  TEXT NOT NULL,
  instagram_url                   TEXT NOT NULL,
  instagram_handle_label           TEXT NOT NULL DEFAULT 'Instagram',

  service_area_fr                 TEXT,
  service_area_en                 TEXT,

  default_seo_title_fr             TEXT NOT NULL,
  default_seo_title_en             TEXT NOT NULL,
  default_seo_description_fr       TEXT NOT NULL,
  default_seo_description_en       TEXT NOT NULL,

  updated_at                      INTEGER NOT NULL,
  updated_by                       TEXT
);


-- ----------------------------------------------------------------------------
-- SEO — one row per known public page (including Confidentialité: SEO
-- metadata is markup, not legal content, so it's in scope even though
-- page_content is not — see DATA_ARCHITECTURE.md §9/§11).
-- ----------------------------------------------------------------------------
CREATE TABLE page_seo (
  page_key             TEXT PRIMARY KEY
                       CHECK (page_key IN
                         ('home', 'work', 'services', 'about', 'contact', 'privacy')),

  title_fr               TEXT NOT NULL,
  title_en               TEXT NOT NULL,
  description_fr         TEXT NOT NULL,
  description_en         TEXT NOT NULL,

  og_media_id            INTEGER REFERENCES media(id) ON DELETE SET NULL,
  canonical_override      TEXT,
  noindex                INTEGER NOT NULL DEFAULT 0 CHECK (noindex IN (0,1)),

  updated_at             INTEGER NOT NULL,
  updated_by               TEXT
);


-- ----------------------------------------------------------------------------
-- CONTENT SNAPSHOTS — rollback safety net, not a full revision system.
-- One JSON snapshot of an entity's own published columns, taken
-- automatically right before each publish action — now uniformly for
-- every publishable entity (Review 009A extended draft/publish, and this
-- snapshot mechanism with it, to work_items/services/testimonials, not
-- just the 5 page-content tables). Pruned to the last N (recommended: 5)
-- per entity. The ONE deliberate, justified exception to "no JSON blob"
-- (ADR-004) — this is an audit/recovery artifact, never rendered, never
-- queried for live content. No FK: entity_type/entity_key is a loose
-- reference by design (see DATA_ARCHITECTURE.md §15).
-- ----------------------------------------------------------------------------
CREATE TABLE content_snapshots (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_type    TEXT NOT NULL
                 CHECK (entity_type IN
                   ('work_item', 'service', 'testimonial', 'home_content',
                    'work_page_content', 'services_page_content',
                    'about_content', 'contact_content')),
  entity_key     TEXT NOT NULL,
  language       TEXT NOT NULL CHECK (language IN ('fr', 'en', 'both')),
  snapshot_json  TEXT NOT NULL,
  created_at     INTEGER NOT NULL,
  created_by      TEXT
);

CREATE INDEX idx_content_snapshots_entity ON content_snapshots(entity_type, entity_key, created_at);


-- ----------------------------------------------------------------------------
-- CONTACT — deliberately NO table (Review 009A).
-- Flow: validation -> Turnstile -> transactional email -> Worker logs.
-- No submission, no IP, no IP hash, nothing about a contact-form
-- submission is stored in D1 at MVP. Observability (was the email sent,
-- did Turnstile pass, is there an abuse spike) is a Worker-logs/alerting
-- concern (Master Brief §58), not a database concern. See
-- DATA_ARCHITECTURE.md §26.
-- ----------------------------------------------------------------------------


-- ============================================================================
-- TRIGGERS — publication-rights gate
-- A work_item or testimonial cannot be published (fr_status/en_status ->
-- 'published') unless its referenced media has confirmed publication
-- rights. Testimonials without a photo (photo_media_id IS NULL) are not
-- gated — see DATA_ARCHITECTURE.md §16/§24.
-- ============================================================================

CREATE TRIGGER trg_work_items_rights_gate_fr
BEFORE UPDATE OF fr_status ON work_items
WHEN NEW.fr_status = 'published'
  AND (SELECT publication_rights_confirmed FROM media WHERE id = NEW.media_id) = 0
BEGIN
  SELECT RAISE(ABORT, 'work_items: cannot publish FR — media publication rights not confirmed');
END;

CREATE TRIGGER trg_work_items_rights_gate_en
BEFORE UPDATE OF en_status ON work_items
WHEN NEW.en_status = 'published'
  AND (SELECT publication_rights_confirmed FROM media WHERE id = NEW.media_id) = 0
BEGIN
  SELECT RAISE(ABORT, 'work_items: cannot publish EN — media publication rights not confirmed');
END;

CREATE TRIGGER trg_testimonials_rights_gate_fr
BEFORE UPDATE OF fr_status ON testimonials
WHEN NEW.fr_status = 'published'
  AND NEW.photo_media_id IS NOT NULL
  AND (SELECT publication_rights_confirmed FROM media WHERE id = NEW.photo_media_id) = 0
BEGIN
  SELECT RAISE(ABORT, 'testimonials: cannot publish FR — photo publication rights not confirmed');
END;

CREATE TRIGGER trg_testimonials_rights_gate_en
BEFORE UPDATE OF en_status ON testimonials
WHEN NEW.en_status = 'published'
  AND NEW.photo_media_id IS NOT NULL
  AND (SELECT publication_rights_confirmed FROM media WHERE id = NEW.photo_media_id) = 0
BEGIN
  SELECT RAISE(ABORT, 'testimonials: cannot publish EN — photo publication rights not confirmed');
END;
